// flow-typed signature: 96ed623db718e3f07ee70249004813b1
// flow-typed version: <<STUB>>/jsdoc-react-proptypes_v^1.0.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-react-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-react-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-react-proptypes/lib/dictionaries/react' {
  declare module.exports: any;
}

declare module 'jsdoc-react-proptypes/lib/plugin' {
  declare module.exports: any;
}

declare module 'jsdoc-react-proptypes/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-react-proptypes/lib/dictionaries/react.js' {
  declare module.exports: $Exports<'jsdoc-react-proptypes/lib/dictionaries/react'>;
}
declare module 'jsdoc-react-proptypes/lib/plugin.js' {
  declare module.exports: $Exports<'jsdoc-react-proptypes/lib/plugin'>;
}
declare module 'jsdoc-react-proptypes/test/test.js' {
  declare module.exports: $Exports<'jsdoc-react-proptypes/test/test'>;
}
