// flow-typed signature: 3b10f3911f7ba77eb4a4a5e790c9499a
// flow-typed version: <<STUB>>/minami_v^1.2.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minami'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minami' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minami/publish' {
  declare module.exports: any;
}

declare module 'minami/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'minami/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'minami/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minami/publish.js' {
  declare module.exports: $Exports<'minami/publish'>;
}
declare module 'minami/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'minami/static/scripts/linenumber'>;
}
declare module 'minami/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'minami/static/scripts/prettify/lang-css'>;
}
declare module 'minami/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'minami/static/scripts/prettify/prettify'>;
}
